version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: interfaces_api_backend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - /app/node_modules

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: interfaces_api_frontend
    environment:
      - NUXT_BACKEND_URL=http://localhost:3000
      - HOST=0.0.0.0
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - backend
    volumes:
      - /app/node_modules

  postgres:
    image: postgres:13
    container_name: interfaces_api_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

networks:
  default:
    driver: bridge